ALTER TABLE "broadcast"."playlist_items" DROP CONSTRAINT "broadcast_playlist_items_source_type_check";--> statement-breakpoint
ALTER TABLE "broadcast"."playlist_items" DROP CONSTRAINT "broadcast_playlist_items_source_shape_check";--> statement-breakpoint
ALTER TABLE "broadcast"."playlist_items" ADD COLUMN "agenda_event_id" text;--> statement-breakpoint
ALTER TABLE "broadcast"."playlist_items" ADD CONSTRAINT "playlist_items_agenda_event_id_agenda_events_id_fk" FOREIGN KEY ("agenda_event_id") REFERENCES "broadcast"."agenda_events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "broadcast"."playlist_items" ADD CONSTRAINT "broadcast_playlist_items_source_type_check" CHECK ("broadcast"."playlist_items"."source_type" in ('local','media-asset','webpage','news','agenda-event'));--> statement-breakpoint
ALTER TABLE "broadcast"."playlist_items" ADD CONSTRAINT "broadcast_playlist_items_source_shape_check" CHECK (("broadcast"."playlist_items"."source_type" = 'local' AND "broadcast"."playlist_items"."relative_path" IS NOT NULL AND "broadcast"."playlist_items"."media_asset_id" IS NULL AND "broadcast"."playlist_items"."url" IS NULL AND "broadcast"."playlist_items"."agenda_event_id" IS NULL)
        OR ("broadcast"."playlist_items"."source_type" = 'media-asset' AND "broadcast"."playlist_items"."media_asset_id" IS NOT NULL AND "broadcast"."playlist_items"."relative_path" IS NULL AND "broadcast"."playlist_items"."url" IS NULL AND "broadcast"."playlist_items"."agenda_event_id" IS NULL)
        OR ("broadcast"."playlist_items"."source_type" = 'webpage' AND "broadcast"."playlist_items"."url" IS NOT NULL AND "broadcast"."playlist_items"."relative_path" IS NULL AND "broadcast"."playlist_items"."media_asset_id" IS NULL AND "broadcast"."playlist_items"."agenda_event_id" IS NULL)
        OR ("broadcast"."playlist_items"."source_type" = 'news' AND "broadcast"."playlist_items"."relative_path" IS NULL AND "broadcast"."playlist_items"."media_asset_id" IS NULL AND "broadcast"."playlist_items"."url" IS NULL AND "broadcast"."playlist_items"."agenda_event_id" IS NULL)
        OR ("broadcast"."playlist_items"."source_type" = 'agenda-event' AND "broadcast"."playlist_items"."agenda_event_id" IS NOT NULL AND "broadcast"."playlist_items"."relative_path" IS NULL AND "broadcast"."playlist_items"."media_asset_id" IS NULL AND "broadcast"."playlist_items"."url" IS NULL));