import {
  Activity,
  ArrowLeftRight,
  Award,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Cake,
  Calendar,
  Camera,
  Church,
  ClipboardList,
  FileText,
  Files,
  FolderTree,
  Globe,
  GraduationCap,
  Handshake,
  HeartHandshake,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Info,
  LayoutList,
  LayoutTemplate,
  LifeBuoy,
  Link2,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Newspaper,
  Palette,
  Phone,
  Puzzle,
  Settings,
  ShieldCheck,
  Star,
  Tag,
  Users,
  Video,
  Wrench,
} from "lucide-react";

// Registro único chave -> componente lucide, compartilhado entre a renderização de main-nav (tema,
// via platform/nav-icons/NavIcon.tsx) e o picker de ícone do editor de menu do CMS
// (app/(platform)/admin/cms/menus). Vive em platform/, não em themes/ ou
// contexts/cms/: a escolha do ícone acontece no CMS (context sem noção de tema), só a
// renderização do ícone escolhido é tema-específica — uma chave nova só precisa entrar aqui pra
// aparecer nos dois lugares ao mesmo tempo. Chaves de admin-nav (platform/admin-shell) têm o
// próprio registro separado, não passam por aqui.
export const NAV_ICON_BY_KEY: Record<string, LucideIcon> = {
  home: Home,
  users: Users,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  image: ImageIcon,
  settings: Settings,
  palette: Palette,
  "layout-template": LayoutTemplate,
  "layout-list": LayoutList,
  "folder-tree": FolderTree,
  files: Files,
  menu: Menu,
  activity: Activity,
  "arrow-left-right": ArrowLeftRight,
  puzzle: Puzzle,
  cake: Cake,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  calendar: Calendar,
  newspaper: Newspaper,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "heart-handshake": HeartHandshake,
  star: Star,
  bell: Bell,
  "message-circle": MessageCircle,
  video: Video,
  camera: Camera,
  globe: Globe,
  building: Building2,
  handshake: Handshake,
  award: Award,
  "clipboard-list": ClipboardList,
  wrench: Wrench,
  "shield-check": ShieldCheck,
  "life-buoy": LifeBuoy,
  tag: Tag,
  "help-circle": HelpCircle,
  info: Info,
  church: Church,
};

export const NAV_ICON_KEYS = Object.keys(NAV_ICON_BY_KEY);

// Fallback genérico quando o item não tem `icon` ou a chave não é (mais) reconhecida — nunca
// quebra, nunca fica sem ícone nenhum.
export const NAV_ICON_FALLBACK: LucideIcon = Link2;
