import type { AdminNavItemDefinition } from "@/platform/admin-shell/admin-navigation.contracts";

export const cmsAdminNavigationItems: AdminNavItemDefinition[] = [
  {
    key: "cms.overview",
    label: "Visão geral",
    icon: "file-text",
    href: "/admin/cms",
    groupKey: "content",
    groupLabel: "Editorial",
    groupOrder: 20,
    order: 10,
    requiredPermission: [
      "cms.entries.manage",
      "cms.content-types.manage",
      "cms.categories.manage",
      "cms.menus.manage",
    ],
  },
  {
    key: "cms.content-types",
    label: "Tags",
    icon: "layout-list",
    href: "/admin/cms/content-types",
    groupKey: "content",
    groupLabel: "Editorial",
    groupOrder: 20,
    order: 20,
    requiredPermission: "cms.content-types.manage",
  },
  {
    key: "cms.categories",
    label: "Categorias",
    icon: "folder-tree",
    href: "/admin/cms/categories",
    groupKey: "content",
    groupLabel: "Editorial",
    groupOrder: 20,
    order: 30,
    requiredPermission: "cms.categories.manage",
  },
  {
    key: "cms.entries",
    label: "Conteúdos",
    icon: "files",
    href: "/admin/cms/entries",
    groupKey: "content",
    groupLabel: "Editorial",
    groupOrder: 20,
    order: 40,
    requiredPermission: "cms.entries.manage",
  },
  {
    key: "cms.menus",
    label: "Navegação",
    icon: "menu",
    href: "/admin/cms/menus",
    groupKey: "content",
    groupLabel: "Editorial",
    groupOrder: 20,
    order: 50,
    requiredPermission: "cms.menus.manage",
  },
];
